"""add parent_message_id to messages

Revision ID: d57ba9ebb251
Revises: 675b5321501b
Create Date: 2024-09-11 10:12:45.826265

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = 'd57ba9ebb251'
down_revision = '675b5321501b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if parent_message_id column exists in messages table
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    messages_columns = [col['name'] for col in inspector.get_columns('messages')]
    
    with op.batch_alter_table('messages', schema=None) as batch_op:
        if 'parent_message_id' not in messages_columns:
            batch_op.add_column(sa.Column('parent_message_id', models.types.StringUUID(), nullable=True))

    # Set parent_message_id for existing messages to uuid_nil() to distinguish them from new messages with actual parent IDs or NULLs
    # Only if the column was just added and all values are NULL
    if 'parent_message_id' not in messages_columns:
        op.execute('UPDATE messages SET parent_message_id = uuid_nil() WHERE parent_message_id IS NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('parent_message_id')

    # ### end Alembic commands ###
